title: The Nursury
email: jon@jonmsterling.com
description: >-
  A mathematical web page.
baseurl: &baseurl "/math"
url: "https://www.jonsmsterling.com/"
twitter_username: jonmsterling
github_username: jonsterling

theme: minima

source : .
destination : ./_site
exclude:
  - compiled


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: null
  parse_block_html: true

antex:
  url_path_prefix: *baseurl

  commands:
    latexmk:
      command:
        - "TEXINPUTS=.:./assets/macros/:${TEXINPUTS}"
        - "latexmk"
        - "-output-directory={{ dir.work }}"
        - "{{ file.tex }}"
      sources:
        - "{{ file.tex }}"
      targets:
        - "{{ file.dvi }}"
        - "{{ file.yml }}"


  aliases: # disable most aliases and use server side AnTeX only for complex LaTeX
    display_math:
      priority: 20
      regexp: !ruby/regexp |
        /«
        (?<code>.*?)
        »/mx
      options:
        prepend: '$\displaystyle '
        append: $
        classes: [antex, display]
    inline_math: false
      #  inline_math:
      #    priority: 10
      #    regexp: !ruby/regexp |
      #      /\$(?<code>.*?)\$/x
      #    options:
      #      prepend: $
      #      append: $
      #      classes: [antex, inline]
    inline_macro: false

plugins:
  - jekyll-feed

collections:
  lectures:
    output: true
    order:
      - topos.md
      - categorical-foundations.md
